#$$$$$$$\                                           $$$$$$\
#$$  __$$\                                         $$  __$$\
#$$ |  $$ | $$$$$$$\ $$\   $$\  $$$$$$$\  $$$$$$\  $$ /  \__|$$$$$$\  $$\   $$\
#$$$$$$$  |$$  _____|$$ |  $$ |$$  _____|$$  __$$\ $$$$\    $$  __$$\ $$ |  $$ |
#$$  ____/ \$$$$$$\  $$ |  $$ |$$ /      $$ /  $$ |$$  _|   $$$$$$$$ |$$ |  $$ |
#$$ |       \____$$\ $$ |  $$ |$$ |      $$ |  $$ |$$ |     $$   ____|$$ |  $$ |
#$$ |      $$$$$$$  |\$$$$$$$ |\$$$$$$$\ \$$$$$$  |$$ |     \$$$$$$$\ \$$$$$$  |
#\__|      \_______/  \____$$ | \_______| \______/ \__|      \_______| \______/
#                    $$\   $$ |
#                    \$$$$$$  |
#                     \______/
# https://discord.gg/vanillamcbe
# https://github.com/psycofeu

welcome_message_enable: true
welcome_message: "§9- §fThe player §9{player} §fjoined server for first time"
welcome_popup_enable: true
welcome_popup: "§9- §fWelcome §9{player} -"
join_message_enable: true
join_message: "§f[§a+§f] - {player}"
join_popup_enable: true
join_popup: "§f[§a+§f] - {player}"
leave_message_enable: true
leave_message: "§f[§c-§f] - {player}"
leave_popup_enable: true
leave_popup: "§f[§c-§f] - {player}"